services:
  ubuntu-base:
    image: ubuntu-base
    build:
      dockerfile: Dockerfile.ubuntu-base
      target: ubuntu-base
  
  sas-base:
    env_file: .env
    image: sas-base
    build:
      dockerfile: Dockerfile.sas-base
      target: sas-base
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_PASSWORD=${GIT_PASSWORD}
        - SAS_USERNAME=${SAS_USERNAME}
        - SAS_PASSWORD=${SAS_PASSWORD}
        - MODE=${MODE}

  sas-development:
    env_file: .env
    image: sas-development
    build:
      dockerfile: Dockerfile
      target: sas-development
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_PASSWORD=${GIT_PASSWORD}
        - GIT_FULL_NAME=${GIT_FULL_NAME}
        - GIT_EMAIL=${GIT_EMAIL}
        - SAS_USERNAME=${SAS_USERNAME}
        - SAS_PASSWORD=${SAS_PASSWORD}
        - MODE=${MODE}