services:
  ubuntu-base:
    image: ubuntu-base
  
  sas-base:
    env_file: .env
    image: sas-base

  sas-development:
    env_file: .env
    image: sas-development
    build:
      dockerfile: Dockerfile
      target: sas-development
      args:
        - SAS_USERNAME=${SAS_USERNAME}
        - SAS_PASSWORD=${SAS_PASSWORD}
